### ISSUE TITLE
Use CSS instead of HTML tables for alignment

### ISSUE THREAD

**Issue by fabian-z** [mzeiher/webengineering#10]
https://github.com/mzeiher/webengineering/blob/8283c05010eeb0feb5379e64e9aad074fbab608d/exercises/html/formdata-validation/formdata-validation.solution.html#L13

See also https://html.spec.whatwg.org/#the-table-element

```
The table element represents data with more than one dimension, in the form of a table.
[..]
Tables must not be used as layout aids.
```

**Comment by mzeiher** [comment]
in this case it's intended, because it's still the "html" lesson without knowledge of css
